### ISSUE TITLE
Version 1.1.0 break on node 0.10 and below

### ISSUE THREAD

**Issue by flyingsky** [tj/node-pwd#10]
1.1.0 code uses ES6 syntax like {salt, hash: xxx}, which is not supported by node 0.12 and below.

**Comment by quocnguyen** [comment]
0.10 and bellow soon will completely UNSUPPORTED in a month. No security fixes.
I think this is time everyone should update to v4 as it is LTS version.

https://github.com/nodejs/LTS

**Comment by flyingsky** [comment]
I agree if it needs a lot change, but actually it just several easy changes.
